# Generated by Django 3.1.1 on 2020-10-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_createorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateOrder',
        ),
    ]
