# Generated by Django 3.1.1 on 2020-10-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_delete_createorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='owner',
        ),
    ]
