# Generated by Django 3.1.1 on 2020-12-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20201027_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='owner',
            new_name='user',
        ),
    ]
