# Generated by Django 3.1.1 on 2020-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20201222_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to=''),
        ),
    ]
