# Generated by Django 3.1.1 on 2020-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20201222_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
